-- Add BAC_CHAIRMAN and BAC_SECRETARY roles to users table
ALTER TABLE users MODIFY COLUMN role ENUM('PROJECT_OWNER', 'PROCUREMENT', 'BAC_CHAIRMAN', 'BAC_SECRETARY', 'SUPERADMIN') NOT NULL DEFAULT 'PROJECT_OWNER';
